export const authConstant = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILED:"LOGIN_FAILED",
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGOUT_REQUEST:"LOGOUT_REQUEST"
};
export const authAdminConstant = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILED:"LOGIN_FAILED",
  LOGIN_SUCCESS:"LOGIN_SUCCESS",
  LOGOUT_REQUEST:"LOGOUT_REQUEST"
};
export const userConstant={
    USER_REGISTER_REQUEST:"USER_REGISTER_REQUEST",
    USER_REGISTER_SUCCESS:"USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILURE:"USER_REGISTER_FAILURE",


}
export const ADD_WISHLIST_ITEM = 'ADD_WISHLIST_ITEM';
export const REMOVE_WISHLIST_ITEM = 'REMOVE_WISHLIST_ITEM';
export const FETCH_WISHLIST = 'FETCH_WISHLIST';
export const WISHLIST_ERROR = 'WISHLIST_ERROR';

export const adminConstant={
ADMIN_REGISTER_REQUEST:"ADMIN_REGISTER_REQUEST",
ADMIN_REGISTER_SUCCESS:"ADMIN_REGISTER_SUCCESS",
ADMIN_REGISTER_FAILURE:"ADMIN_REGISTER_FAILURE",
UPDATE_ORDER_STATUS_REQUEST:"UPDATE_ORDER_STATUS_REQUEST",
UPDATE_ORDER_STATUS_SUCCESS:"UPDATE_ORDER_STATUS_SUCCESS",
UPDATE_ORDER_STATUS_FAILURE:"UPDATE_ORDER_STATUS_FAILURE"
// constants.js
}

export const categoryConstant = {
    GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
    GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
    GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",
    ADD_CATEGORY_REQUEST: "ADD_CATEGORY_REQUEST",
    ADD_CATEGORY_SUCCESS: "ADD_CATEGORY_SUCCESS",
    ADD_CATEGORY_FAILURE: "ADD_CATEGORY_FAILURE",
    UPDATE_CATEGORY_REQUEST: "UPDATE_CATEGORY_REQUEST",
    UPDATE_CATEGORY_SUCCESS: "UPDATE_CATEGORY_SUCCESS",
    UPDATE_CATEGORY_FAILURE: "UPDATE_CATEGORY_FAILURE",
    DELETE_CATEGORY_REQUEST:"DELETE_CATEGORY_REQUEST",
    DELETE_CATEGORY_SUCCESS:"DELETE_CATEGORY_SUCCESS",
    DELETE_CATEGORY_FAILURE:"DELETE_CATEGORY_FAILURE",
    // Other category-related constants
};
// productConstants.js
export const productConstants = {
    ADD_PRODUCT_REQUEST: 'ADD_PRODUCT_REQUEST',
    ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAILURE: 'ADD_PRODUCT_FAILURE',
    GET_PRODUCT_BY_CAT_REQUEST:'GET_PRODUCT_BY_CAT_REQUEST',
    GET_PRODUCT_BY_CAT_SUCCESS:'GET_PRODUCT_BY_CAT_SUCCESS',
    GET_PRODUCT_BY_CAT_FAILURE:'GET_PRODUCT_BY_CAT_FAILURE',
    GET_RELATED_PRODUCTS_REQUEST:'GET_RELATED_PRODUCTS_REQUEST',
    GET_RELATED_PRODUCTS_SUCCESS:'GET_RELATED_PRODUCTS_SUCCESS',
    GET_RELATED_PRODUCTS_FAILURE:'GET_RELATED_PRODUCTS_FAILURE',
    GET_FEATURED_PRODUCTS_REQUEST:'GET_FEATURED_PRODUCTS_REQUEST',
    GET_FEATURED_PRODUCTS_SUCCESS:'GET_FEATURED_PRODUCTS_SUCCESS',
    GET_FEATURED_PRODUCTS_FAILURE:'GET_FEATURED_PRODUCTS_FAILURE',
    GET_ALL_PRODUCTS_REQUEST:'GET_ALL_PRODUCTS_REQUEST',
    GET_ALL_PRODUCTS_SUCCESS:'GET_ALL_PRODUCTS_SUCCESS',
    GET_ALL_PRODUCTS_FAILURE:'GET_ALL_PRODUCTS_FAILURE',
    DELETE_PRODUCT_REQUEST:'DELETE_PRODUCT_REQUEST',
    DELETE_PRODUCT_SUCCESS:'DELETE_PRODUCT_SUCCESS',

    DELETE_PRODUCT_FAILURE:'DELETE_PRODUCT_FAILURE',
    UPDATE_PRODUCT_REQUEST:'UPDATE_PRODUCT_REQUEST',
    UPDATE_PRODUCT_SUCCESS:'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_FAILURE:'UPDATE_PRODUCT_FAILURE',


    // Add more action types as needed
  };
  export const searchConstants={
    SEARCH_PRODUCT_REQUEST:'SEARCH_PRODUCT_REQUEST',
    SEARCH_PRODUCT_SUCCESS:'SEARCH_PRODUCT_SUCCESS',
    SEARCH_PRODUCT_FAILURE:'SEARCH_PRODUCT_FAILURE',
   
  }
export const productFetchId={
  GET_PRODUCT_ID_REQUEST:'GET_PRODUCT_ID_REQUEST',
  GET_PRODUCT_ID_SUCCESS:'GET_PRODUCT_ID_SUCCESS',
  GET_PRODUCT_ID_FAILURE:'GET_PRODUCT_ID_FAILURE',
  GET_RATING:'GET_RATING',
}
  export const InitialData = {
    FETCH_INITIAL_DATA_REQUEST: 'FETCH_INITIAL_DATA_REQUEST',
    FETCH_INITIAL_DATA_SUCCESS: 'FETCH_INITIAL_DATA_SUCCESS',
    FETCH_INITIAL_DATA_FAILURE: 'FETCH_INITIAL_DATA_FAILURE',
  };
  
  export const InitialProductData={
    FETCH_INITIAL_PRODUCT_DATA_REQUEST: 'FETCH_INITIAL_PRODUCT_DATA_REQUEST',
    FETCH_INITIAL_PRODUCT_DATA_SUCCESS: 'FETCH_INITIAL_PRODUCT_DATA_SUCCESS',
    FETCH_INITIAL_PRODUCT_DATA_FAILURE: 'FETCH_INITIAL_PRODUCT_DATA_FAILURE',
  }
  export const productConstantData={
 GET_PRODUCTS_BY_SLUG:'GET_PRODUCTS_BY_SLUG',
 

  }
  // pageConstants.js
export const pageConstants = {
  CREATE_PAGE_REQUEST: 'CREATE_PAGE_REQUEST',
  CREATE_PAGE_SUCCESS: 'CREATE_PAGE_SUCCESS',
  CREATE_PAGE_FAILURE: 'CREATE_PAGE_FAILURE',
  // Add more action types as needed
};
export const pageGetConstants={
  GET_PAGE_REQUEST:'GET_PAGE_REQUEST',
  GET_PAGE_SUCCESS:'GET_PAGE_SUCCESS',
  GET_PAGE_FAILURE:'GET_PAGE_FAILURE',
}
export const cartConstants={



  ADD_TO_CART_REQUEST:'ADD_TO_CART_REQUEST',
  ADD_TO_CART_SUCCESS:'ADD_TO_CART_SUCCESS',
  ADD_TO_CART_FAILURE:'ADD_TO_CART_FAILURE',
  REMOVE_FROM_CART_REQUEST:'REMOVE_FROM_CART_REQUEST',
  REMOVE_FROM_CART_SUCCESS:'REMOVE_FROM_CART_SUCCESS',
  REMOVE_FROM_CART_FAILURE:'REMOVE_FROM_CART_FAILURE',
  GET_CART_ITEMS_REQUEST:'GET_CART_ITEMS_REQUEST',
  GET_CART_ITEMS_SUCCESS:'GET_CART_ITEMS_SUCCESS',
  GET_CART_ITEMS_FAILURE:'GET_CART_ITEMS_FAILURE',
  RESET_CART:'RESET_CART',

  REMOVE_CART:'REMOVE_CART',
  
}
export const addressConstants={
  ADD_USER_ADDRESS_REQUEST:'ADD_USER_ADDRESS_REQUEST',
  ADD_USER_ADDRESS_SUCCESS:'ADD_USER_ADDRESS_SUCCESS',
  ADD_USER_ADDRESS_FAILURE:'ADD_USER_ADDRESS_FAILURE',
  GET_USER_ADDRESS_REQUEST:'GET_USER_ADDRESS_REQUEST',
  GET_USER_ADDRESS_SUCCESS:'GET_USER_ADDRESS_SUCCESS',
  GET_USER_ADDRESS_FAILURE:'GET_USER_ADDRESS_FAILURE',
  SET_SELECTED_ADDRESS:'SET_SELECTED_ADDRESS',
  UPDATE_USER_ADDRESS_REQUEST:'UPDATE_USER_ADDRESS_REQUEST',
  UPDATE_USER_ADDRESS_SUCCESS:'UPDATE_USER_ADDRESS_SUCCESS',
  UPDATE_USER_ADDRESS_FAILURE:'UPDATE_USER_ADDRESS_FAILURE',
  ADD_ORDER_REQUEST:'ADD_ORDER_REQUEST',
  ADD_ORDER_SUCCESS:'ADD_ORDER_SUCCESS',
  ADD_ORDER_FAILURE:'ADD_ORDER_FAILURE',
  GET_ORDER_REQUEST:'GET_ORDER_REQUEST',
  GET_ORDER_SUCCESS:'GET_ORDER_SUCCESS',
  GET_ORDER_FAILURE:'GET_ORDER_FAILURE',
  GET_ADMIN_ORDER_REQUEST:'GET_ADMIN_ORDER_REQUEST',
  GET_ADMIN_ORDER_SUCCESS:'GET_ADMIN_ORDER_SUCCESS',
  GET_ADMIN_ORDER_FAILURE:'GET_ADMIN_ORDER_FAILURE',


}
export const clearRelatedProducts={
  CLEAR_RELATED_PRODUCTS : 'CLEAR_RELATED_PRODUCTS',
}
export const reviewProducts={
  CREATE_REVIEW_PRODUCT_REQUEST:'CREATE_REVIEW_PRODUCT_REQUEST',
  CREATE_REVIEW_PRODUCT_SUCCESS:'CREATE_REVIEW_PRODUCT_SUCCESS',
  CREATE_REVIEW_PRODUCT_FAILURE:'CREATE_REVIEW_PRODUCT_FAILURE',
  GET_ALL_REVIEW_PRODUCT_REQUEST:'GET_ALL_REVIEW_PRODUCT_REQUEST',
  GET_ALL_REVIEW_PRODUCT_SUCCESS:'GET_ALL_REVIEW_PRODUCT_SUCCESS',
  GET_ALL_REVIEW_PRODUCT_FAILURE:'GET_ALL_REVIEW_PRODUCT_FAILURE',

}